[project]
name = "xm-spotify-sync"
version = "0.1.0"
requires-python = ">=3.13"

[tool.uv.workspace]
members = ["src/backend", "src/frontend"]

[tool.uv]
dev-dependencies = ["pytest>=8.3.0", "ruff>=0.8.0"]
